#!/bin/sh
PATH=/usr/local/bin:/usr/local/sbin:~/bin:/usr/bin:/bin:/usr/sbin:/sbin

TOKEN="placeholder"
URL="https://slack.com/api/users.profile.set"

STATUS=`osascript <<-AppleScript

set appName to "Spotify"

if application "Spotify" is running then
	tell application "Spotify"
		if player state is playing then
			return "Listening to " & (get name of current track) & " by " & (get artist of current track)
		else
			return ""
		end if
	end tell
else
	return ""
end if
AppleScript`

curl -v -sS -d 'token='$TOKEN --data-urlencode 'profile={ "status_text": "'"$STATUS"'", "status_emoji": ":spotify:" }' $URL
